### ISSUE TITLE
Adds Sports generator

### ISSUE THREAD

**Issue by acrosman** [SFDO-Community-Sprints/Snowfakery-Edu#22]
## Feature Description

Add a function to generator common college sports

## Proposed Solution

This could be built from the list of [NCAA sponsored sports](https://en.wikipedia.org/wiki/National_Collegiate_Athletic_Association#NCAA_sponsored_sports), with some non-US additions like Cricket. College sports programs are typically gendered so having gendered versions would be useful (e.g. Soccer vs Women's Soccer vs Men's Soccer).  We can leave Soccer vs Football to an internationalize effort.

Please include test coverage.

**Comment by bybwang** [comment]
Hi! I'm new to open source and would love to contribute. I opened a pull request for this issue if you could take a look.
