### ISSUE TITLE
Facilities Name Generator

### ISSUE THREAD

**Issue by acrosman** [SFDO-Community-Sprints/Snowfakery-Edu#23]
## Feature Description

College frequently name their buildings after a person who paid for it, or sometimes after a purpose.

## Proposed Solution

Start with a basic facilities generator that is something to the effect of: 
{Last_name} {Discipline Name} {Hall|Library|Building|Center|...}

An extra level would include an  optional filter to select building type (Library, Residence Hall, Gym, etc).

Please include test coverage.

**Comment by bybwang** [comment]
Hi! I'm new to open source and would love to contribute. I opened a pull request for this issue if you could take a look.

**Comment by acrosman** [comment]
Yes, I see your PRs. Thank you very much for contributing. I'm a little behind in reviewing them (I had a very busy work week), but I should be able to take a look in the next couple days.  One minor tip about contributing to github projects, you can put a reference to the issue you are addressing the description or a comment on your PR so they get linked together automatically.  

For example if I'll put `#26`  after this sentence and github will make that a reference to your related pull request:  #26 If you go look at the discussion tab there you can see this comment mentioned.  If you do the reverse put `closes #23`  as a comment on that PR it'll setup the system so that when we merge those PRs the related issue will also close.
